name: Deploy to prd
on: [push]
env:
  tf_version: '1.1.9'
  tg_version: '0.37.0'
  tf_working_dir: './modules'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive ${{ env.tf_working_dir }}
  
  plan_prd:
    needs: lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Terragrunt Plan
        run: |
          export DEPLOY_ENV=prd
          export AWS_ACCESS_KEY_ID="${{secrets.IAC_AWS_ACCESS_KEY_ID}}"
          export AWS_SECRET_ACCESS_KEY="${{secrets.IAC_AWS_SECRET_ACCESS_KEY}}"
          ./scripts/plan.sh
  
  apply_prd:
    needs: plan_prd
    runs-on: ubuntu-latest
    environment:
      name: prd-env
    steps: 
      - uses: actions/checkout@v3
      - name: "Terragrunt Apply"
        run: |
          export DEPLOY_ENV=prd
          export AWS_ACCESS_KEY_ID="${{secrets.IAC_AWS_ACCESS_KEY_ID}}"
          export AWS_SECRET_ACCESS_KEY="${{secrets.IAC_AWS_SECRET_ACCESS_KEY}}"
          ./scripts/apply.sh

