name: Deploy
on: [push]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: "Terragrunt Plan"
        run: >
          export AWS_ACCESS_KEY_ID="${{secrets.IAC_AWS_ACCESS_KEY_ID}}"
          export AWS_SECRET_ACCESS_KEY="${{secrets.IAC_AWS_SECRET_ACCESS_KEY}}"
          ./scripts/deploy.sh plan
  
  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: "Terragrunt Apply"
        run: >
          export AWS_ACCESS_KEY_ID="${{secrets.IAC_AWS_ACCESS_KEY_ID}}"
          export AWS_SECRET_ACCESS_KEY="${{secrets.IAC_AWS_SECRET_ACCESS_KEY}}"
          ./scripts/deploy.sh apply

